# -*- coding: utf-8 -*-
"""hw_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PbZn33wpVpMpO0qyJqkhJCkQ6_fyXB9T
"""

import pandas as pd
import streamlit as st
import pickle

def rg_predict(X_in, model_path):
  with open(model_path, 'rb') as file:
    model = pickle.load(file)

    df_cols = ['city', 'source']
    df_1 = X_in.drop(columns = df_cols, axis = 1)

    # Список всех возможных городов и источников
    all_cities = ['Балашиха',
      'Видное',
      'Дзержинский',
      'Долгопрудный',
      'Ивантеевка',
      'Королёв',
      'Котельники',
      'Красногорск',
      'Лобня',
      'Лыткарино',
      'Люберцы',
      'Москва',
      'Московский',
      'Мытищи',
      'Одинцово',
      'Подольск',
      'Пушкино',
      'Реутов',
      'Химки',
      'Щербинка',
      'Щёлково']

    all_sources = ["Домклик", "Новострой-М", "ЦИАН", "Яндекс.Недвижимость"]

    # Удаляем категориальные признаки
    df_cols = ['city', 'source']
    df_1 = X_in.drop(columns=df_cols, axis=1)

    # Создаем фиктивные переменные с учетом всех возможных категорий
    df_2 = pd.get_dummies(X_in[df_cols], columns=['city', 'source'])
    df_2 = df_2.reindex(columns=[f'city_{city}' for city in all_cities] + [f'source_{source}' for source in all_sources], fill_value=0)

    X_in = pd.concat([df_1, df_2], axis=1, join='inner')

    preds = model.predict(X_in)
  return preds

model_path = 'rf_fitted.pkl'

st.set_page_config(page_title="Real Estate App")

# Интерфейс
st.title("Real Estate Price Prediction")
st.write("Enter the details below to get a price prediction.")

postcode = st.sidebar.number_input("Postcode", 0, 150000, 100000)
lat = st.sidebar.number_input("Lat", 0, 90, 30)
lon = st.sidebar.number_input("Lon", 0, 180, 50)
total_square = st.sidebar.number_input("Total_square", 0, 2070, 50)
rooms = st.sidebar.selectbox("Num of rooms", [x for x in range(14)], index=1)
floor = st.sidebar.number_input(
    "Floor", 2, 66, 5
)
city = st.sidebar.selectbox("City", ['Балашиха',
 'Видное',
 'Дзержинский',
 'Долгопрудный',
 'Ивантеевка',
 'Королёв',
 'Котельники',
 'Красногорск',
 'Лобня',
 'Лыткарино',
 'Люберцы',
 'Москва',
 'Московский',
 'Мытищи',
 'Одинцово',
 'Подольск',
 'Пушкино',
 'Реутов',
 'Химки',
 'Щербинка',
 'Щёлково'], index=0)
source = st.sidebar.selectbox("Source", ["Домклик", "Новострой-М", "ЦИАН", "Яндекс.Недвижимость"], index=0)

inputDF = pd.DataFrame(
    {
      "postcode": postcode,
      "lat": lat,
      "lon": lon,
      "total_square": total_square,
      "rooms": rooms,
      "floor": floor,
      "city": city,
      "source": source,
    },
    index=[0],
)

"""Реализуйте отображение результата прогнозирования в интерфейсе по нажатию кнопки - 2 балла"""
# Инициализация состояния кнопки
if 'clicked' not in st.session_state:
    st.session_state.clicked = False
if 'preds' not in st.session_state:
    st.session_state.preds = None

def click_button():
    st.session_state.clicked = True
    st.session_state.preds = rg_predict(inputDF, model_path)

st.button('Get price', on_click=click_button)

# Отображение результата
if st.session_state.clicked and st.session_state.preds is not None:
    st.write(f"Predicted price: {st.session_state.preds[0]}")
